/* EXTRA PHRASES — Part 1: Conversation, Transport, Temps */
const PHRASES_EXTRA1 = [

  /* ===== РАЗГОВОР — nouvelles phrases ===== */
  {id:41,category:"conversation",level:"A1",russian:"Здравствуйте!",phonetic:"Zdravstvuyte!",fr:"Bonjour !",en:"Hello!"},
  {id:42,category:"conversation",level:"A1",russian:"Привет!",phonetic:"Privet!",fr:"Salut !",en:"Hi!"},
  {id:43,category:"conversation",level:"A1",russian:"Как дела?",phonetic:"Kak dela?",fr:"Comment ça va ?",en:"How are you?"},
  {id:44,category:"conversation",level:"A1",russian:"Спасибо, хорошо.",phonetic:"Spasibo, khorosho.",fr:"Merci, ça va.",en:"Fine, thank you."},
  {id:45,category:"conversation",level:"A1",russian:"А у вас?",phonetic:"A u vas?",fr:"Et vous ?",en:"And you?"},
  {id:46,category:"conversation",level:"A1",russian:"Извините.",phonetic:"Izvinite.",fr:"Pardon.",en:"Excuse me."},
  {id:47,category:"conversation",level:"A1",russian:"Простите.",phonetic:"Prostite.",fr:"Je suis désolé(e).",en:"I am sorry."},
  {id:48,category:"conversation",level:"A1",russian:"Пожалуйста (в ответ на «спасибо»).",phonetic:"Pozhaluysta.",fr:"De rien.",en:"You're welcome."},
  {id:49,category:"conversation",level:"A1",russian:"Пожалуйста (просьба).",phonetic:"Pozhaluysta.",fr:"S'il vous plaît.",en:"Please."},
  {id:50,category:"conversation",level:"A1",russian:"До свидания!",phonetic:"Do svidaniya!",fr:"Au revoir !",en:"Goodbye!"},
  {id:51,category:"conversation",level:"A1",russian:"Пока!",phonetic:"Poka!",fr:"À bientôt !",en:"See you!"},
  {id:52,category:"conversation",level:"A1",russian:"Хорошего дня!",phonetic:"Khoroshego dnya!",fr:"Bonne journée !",en:"Have a nice day!"},
  {id:53,category:"conversation",level:"A1",russian:"Спокойной ночи!",phonetic:"Spokоynoy nochi!",fr:"Bonne nuit !",en:"Good night!"},
  {id:54,category:"conversation",level:"A1",russian:"Меня зовут…",phonetic:"Menya zovut…",fr:"Je m'appelle…",en:"My name is…"},
  {id:55,category:"conversation",level:"A1",russian:"Как вас зовут?",phonetic:"Kak vas zovut?",fr:"Comment vous appelez-vous ?",en:"What is your name?"},
  {id:56,category:"conversation",level:"A1",russian:"Откуда вы?",phonetic:"Otkuda vy?",fr:"D'où venez-vous ?",en:"Where are you from?"},
  {id:57,category:"conversation",level:"A1",russian:"Я из Франции.",phonetic:"Ya iz Frantsii.",fr:"Je viens de France.",en:"I come from France."},
  {id:58,category:"conversation",level:"A1",russian:"Вы говорите по-английски?",phonetic:"Vy govorite po-angliyski?",fr:"Parlez-vous anglais ?",en:"Do you speak English?"},
  {id:59,category:"conversation",level:"A1",russian:"Я не понимаю.",phonetic:"Ya ne ponimayu.",fr:"Je ne comprends pas.",en:"I don't understand."},
  {id:60,category:"conversation",level:"A1",russian:"Повторите, пожалуйста.",phonetic:"Povtorite, pozhaluysta.",fr:"Répétez, s'il vous plaît.",en:"Please repeat that."},
  {id:61,category:"conversation",level:"A1",russian:"Медленнее, пожалуйста.",phonetic:"Medlennee, pozhaluysta.",fr:"Plus lentement, s'il vous plaît.",en:"More slowly, please."},
  {id:62,category:"conversation",level:"A1",russian:"Где находится…?",phonetic:"Gde nakhoditsya…?",fr:"Où se trouve… ?",en:"Where is…?"},
  {id:63,category:"conversation",level:"A1",russian:"Сколько это стоит?",phonetic:"Skol'ko eto stoit?",fr:"Combien cela coûte-t-il ?",en:"How much does this cost?"},
  {id:64,category:"conversation",level:"A1",russian:"Можно мне…?",phonetic:"Mozhno mne…?",fr:"Est-ce que je peux avoir… ?",en:"Can I have…?"},
  {id:65,category:"conversation",level:"A1",russian:"Помогите мне, пожалуйста.",phonetic:"Pomogite mne, pozhaluysta.",fr:"Aidez-moi, s'il vous plaît.",en:"Help me, please."},
  {id:66,category:"conversation",level:"A1",russian:"Большое спасибо!",phonetic:"Bol'shoye spasibo!",fr:"Merci beaucoup !",en:"Thank you very much!"},
  {id:67,category:"conversation",level:"A1",russian:"Без проблем.",phonetic:"Bez problem.",fr:"Pas de problème.",en:"No problem."},
  {id:68,category:"conversation",level:"A1",russian:"Всё в порядке.",phonetic:"Vsyo v poryadke.",fr:"Tout va bien.",en:"Everything is fine."},
  {id:69,category:"conversation",level:"A2",russian:"Я согласен(а).",phonetic:"Ya soglasen(a).",fr:"Je suis d'accord.",en:"I agree."},
  {id:70,category:"conversation",level:"A2",russian:"Я не согласен(а).",phonetic:"Ya ne soglasen(a).",fr:"Je ne suis pas d'accord.",en:"I disagree."},
  {id:71,category:"conversation",level:"A1",russian:"Да.",phonetic:"Da.",fr:"Oui.",en:"Yes."},
  {id:72,category:"conversation",level:"A1",russian:"Нет.",phonetic:"Net.",fr:"Non.",en:"No."},
  {id:73,category:"conversation",level:"A1",russian:"Возможно.",phonetic:"Vozmozhno.",fr:"Peut-être.",en:"Maybe."},
  {id:74,category:"conversation",level:"A1",russian:"Конечно.",phonetic:"Konechno.",fr:"Bien sûr.",en:"Of course."},
  {id:75,category:"conversation",level:"A1",russian:"Я устал(а).",phonetic:"Ya ustal(a).",fr:"Je suis fatigué(e).",en:"I am tired."},
  {id:76,category:"conversation",level:"A1",russian:"Я голоден(а).",phonetic:"Ya goloden(a).",fr:"J'ai faim.",en:"I am hungry."},
  {id:77,category:"conversation",level:"A1",russian:"Я хочу пить.",phonetic:"Ya khochu pit'.",fr:"J'ai soif.",en:"I am thirsty."},
  {id:78,category:"conversation",level:"A1",russian:"Мне холодно.",phonetic:"Mne kholodno.",fr:"J'ai froid.",en:"I am cold."},
  {id:79,category:"conversation",level:"A1",russian:"Мне жарко.",phonetic:"Mne zharko.",fr:"J'ai chaud.",en:"I am hot."},
  {id:80,category:"conversation",level:"A1",russian:"Что это?",phonetic:"Chto eto?",fr:"Qu'est-ce que c'est ?",en:"What is this?"},
  {id:81,category:"conversation",level:"A1",russian:"Кто это?",phonetic:"Kto eto?",fr:"Qui est-ce ?",en:"Who is this?"},
  {id:82,category:"conversation",level:"A1",russian:"Когда?",phonetic:"Kogda?",fr:"Quand ?",en:"When?"},
  {id:83,category:"conversation",level:"A1",russian:"Почему?",phonetic:"Pochemu?",fr:"Pourquoi ?",en:"Why?"},
  {id:84,category:"conversation",level:"A1",russian:"Как?",phonetic:"Kak?",fr:"Comment ?",en:"How?"},
  {id:85,category:"conversation",level:"A1",russian:"Где?",phonetic:"Gde?",fr:"Où ?",en:"Where?"},
  {id:86,category:"conversation",level:"A2",russian:"Что случилось?",phonetic:"Chto sluchilos'?",fr:"Qu'est-ce qui s'est passé ?",en:"What happened?"},
  {id:87,category:"conversation",level:"A1",russian:"Ничего страшного.",phonetic:"Nichego strashnogo.",fr:"Ce n'est rien.",en:"It's nothing."},
  {id:88,category:"conversation",level:"A1",russian:"Увидимся позже.",phonetic:"Uvidimsya pozhe.",fr:"On se voit plus tard.",en:"See you later."},
  {id:89,category:"conversation",level:"A1",russian:"Будьте здоровы!",phonetic:"Bud'te zdorovy!",fr:"À vos souhaits !",en:"Bless you!"},

  /* ===== ТРАНСПОРТ (Transport) ===== */
  {id:90,category:"transport",level:"A1",russian:"Где здесь остановка автобуса?",phonetic:"Gde zdes' ostanovka avtobusa?",fr:"Où est l'arrêt de bus ici ?",en:"Where is the bus stop here?"},
  {id:91,category:"transport",level:"A1",russian:"Как добраться до центра?",phonetic:"Kak dobrat'sya do tsentra?",fr:"Comment aller au centre ?",en:"How do I get to the centre?"},
  {id:92,category:"transport",level:"A1",russian:"Это далеко?",phonetic:"Eto daleko?",fr:"C'est loin ?",en:"Is it far?"},
  {id:93,category:"transport",level:"A2",russian:"Можно доехать на метро?",phonetic:"Mozhno doyekhat' na metro?",fr:"Peut-on y aller en métro ?",en:"Can I get there by metro?"},
  {id:94,category:"transport",level:"A1",russian:"Где купить билет?",phonetic:"Gde kupit' bilet?",fr:"Où peut-on acheter un billet ?",en:"Where can I buy a ticket?"},
  {id:95,category:"transport",level:"A2",russian:"Когда отправляется следующий поезд?",phonetic:"Kogda otpravlyaetsya sleduyushchiy poyezd?",fr:"Quand part le prochain train ?",en:"When does the next train leave?"},
  {id:96,category:"transport",level:"A1",russian:"На какой платформе?",phonetic:"Na kakoy platforme?",fr:"Sur quel quai ?",en:"On which platform?"},
  {id:97,category:"transport",level:"A2",russian:"Мне нужно в аэропорт.",phonetic:"Mne nuzhno v aeroport.",fr:"Je dois aller à l'aéroport.",en:"I need to get to the airport."},
  {id:98,category:"transport",level:"A1",russian:"Вызовите такси, пожалуйста.",phonetic:"Vyzovite taksi, pozhaluysta.",fr:"Appelez un taxi, s'il vous plaît.",en:"Please call a taxi."},
  {id:99,category:"transport",level:"A2",russian:"Сколько будет стоить поездка до отеля?",phonetic:"Skol'ko budet stoit' poyezdka do otelya?",fr:"Combien coûtera le trajet jusqu'à l'hôtel ?",en:"How much will the ride to the hotel cost?"},
  {id:100,category:"transport",level:"A1",russian:"Идите прямо.",phonetic:"Idite pryamo.",fr:"Allez tout droit.",en:"Go straight ahead."},
  {id:101,category:"transport",level:"A1",russian:"Поверните налево.",phonetic:"Povernte nalevo.",fr:"Tournez à gauche.",en:"Turn left."},
  {id:102,category:"transport",level:"A1",russian:"Поверните направо.",phonetic:"Povernte napravo.",fr:"Tournez à droite.",en:"Turn right."},
  {id:103,category:"transport",level:"A1",russian:"Пересеките улицу.",phonetic:"Peresekite ulitsu.",fr:"Traversez la rue.",en:"Cross the street."},
  {id:104,category:"transport",level:"A1",russian:"Это рядом.",phonetic:"Eto ryadom.",fr:"C'est tout près.",en:"It is nearby."},
  {id:105,category:"transport",level:"A1",russian:"Это в пяти минутах ходьбы.",phonetic:"Eto v pyati minutakh khod'by.",fr:"C'est à cinq minutes à pied.",en:"It is five minutes on foot."},
  {id:106,category:"transport",level:"A1",russian:"Где ближайшая станция метро?",phonetic:"Gde blizhayshaya stantsiya metro?",fr:"Où se trouve la station de métro la plus proche ?",en:"Where is the nearest metro station?"},
  {id:107,category:"transport",level:"A1",russian:"Где можно взять карту города?",phonetic:"Gde mozhno vzyat' kartu goroda?",fr:"Où puis-je obtenir une carte de la ville ?",en:"Where can I get a city map?"},
  {id:108,category:"transport",level:"A1",russian:"Я заблудился(ась).",phonetic:"Ya zabludilsya (zablуdilas').",fr:"Je suis perdu(e).",en:"I am lost."},
  {id:109,category:"transport",level:"A1",russian:"Помогите мне найти этот адрес.",phonetic:"Pomogite mne nayti etot adres.",fr:"Aidez-moi à trouver cette adresse.",en:"Help me find this address."},
  {id:110,category:"transport",level:"A1",russian:"Где здесь туалет?",phonetic:"Gde zdes' tualet?",fr:"Où sont les toilettes ?",en:"Where is the toilet here?"},
  {id:111,category:"transport",level:"A1",russian:"Где ближайший банкомат?",phonetic:"Gde blizhayshiy bankomat?",fr:"Où est le distributeur de billets le plus proche ?",en:"Where is the nearest ATM?"},
  {id:112,category:"transport",level:"A1",russian:"Где почта?",phonetic:"Gde pochta?",fr:"Où est la poste ?",en:"Where is the post office?"},
  {id:113,category:"transport",level:"A1",russian:"Где больница?",phonetic:"Gde bol'nitsa?",fr:"Où est l'hôpital ?",en:"Where is the hospital?"},
  {id:114,category:"transport",level:"A1",russian:"Где полицейский участок?",phonetic:"Gde politseyskiy uchastok?",fr:"Où se trouve le commissariat de police ?",en:"Where is the police station?"},
  {id:115,category:"transport",level:"A1",russian:"Где аптека?",phonetic:"Gde apteka?",fr:"Où est la pharmacie ?",en:"Where is the pharmacy?"},
  {id:116,category:"transport",level:"A1",russian:"Где ресторан?",phonetic:"Gde restoran?",fr:"Où est un restaurant ?",en:"Where is a restaurant?"},
  {id:117,category:"transport",level:"A1",russian:"Где кафе?",phonetic:"Gde kafe?",fr:"Où est un café ?",en:"Where is a café?"},
  {id:118,category:"transport",level:"A1",russian:"Где супермаркет?",phonetic:"Gde supermarket?",fr:"Où est un supermarché ?",en:"Where is a supermarket?"},

  /* ===== ВРЕМЯ (Temps / Time) ===== */
  {id:119,category:"temps",level:"A1",russian:"Который час?",phonetic:"Kotoryy chas?",fr:"Quelle heure est-il ?",en:"What time is it?"},
  {id:120,category:"temps",level:"A1",russian:"Сейчас восемь часов.",phonetic:"Seychas vosem' chasov.",fr:"Il est huit heures.",en:"It is eight o'clock."},
  {id:121,category:"temps",level:"A1",russian:"В девять часов.",phonetic:"V devyat' chasov.",fr:"À neuf heures.",en:"At nine o'clock."},
  {id:122,category:"temps",level:"A1",russian:"Завтра утром.",phonetic:"Zavtra utrom.",fr:"Demain matin.",en:"Tomorrow morning."},
  {id:123,category:"temps",level:"A1",russian:"После обеда.",phonetic:"Posle obeda.",fr:"Après le déjeuner.",en:"After lunch."},
  {id:124,category:"temps",level:"A1",russian:"Вечером.",phonetic:"Vecherom.",fr:"Le soir.",en:"In the evening."},
  {id:125,category:"temps",level:"A1",russian:"Сегодня вечером.",phonetic:"Segodnya vecherom.",fr:"Ce soir.",en:"This evening."},
  {id:126,category:"temps",level:"A1",russian:"В выходные.",phonetic:"V vykhodnyye.",fr:"Pendant le week-end.",en:"At the weekend."},
  {id:127,category:"temps",level:"A1",russian:"В понедельник.",phonetic:"V ponedel'nik.",fr:"Lundi.",en:"On Monday."},
  {id:128,category:"temps",level:"A1",russian:"Во вторник.",phonetic:"Vo vtornik.",fr:"Mardi.",en:"On Tuesday."},
  {id:129,category:"temps",level:"A1",russian:"В среду.",phonetic:"V sredu.",fr:"Mercredi.",en:"On Wednesday."},
  {id:130,category:"temps",level:"A1",russian:"В четверг.",phonetic:"V chetverg.",fr:"Jeudi.",en:"On Thursday."},
  {id:131,category:"temps",level:"A1",russian:"В пятницу.",phonetic:"V pyatnitsu.",fr:"Vendredi.",en:"On Friday."},
  {id:132,category:"temps",level:"A1",russian:"В субботу.",phonetic:"V subbotu.",fr:"Samedi.",en:"On Saturday."},
  {id:133,category:"temps",level:"A1",russian:"В воскресенье.",phonetic:"V voskresen'ye.",fr:"Dimanche.",en:"On Sunday."},
  {id:134,category:"temps",level:"A1",russian:"Вчера.",phonetic:"Vchera.",fr:"Hier.",en:"Yesterday."},
  {id:135,category:"temps",level:"A1",russian:"Сегодня.",phonetic:"Segodnya.",fr:"Aujourd'hui.",en:"Today."},
  {id:136,category:"temps",level:"A1",russian:"Завтра.",phonetic:"Zavtra.",fr:"Demain.",en:"Tomorrow."},
  {id:137,category:"temps",level:"A1",russian:"Через час.",phonetic:"Cherez chas.",fr:"Dans une heure.",en:"In one hour."},
  {id:138,category:"temps",level:"A1",russian:"Скоро.",phonetic:"Skoro.",fr:"Bientôt.",en:"Soon."}
];
