/* EXTRA PHRASES — Part 3: Santé + Logement */
const PHRASES_EXTRA3 = [

  /* ===== ЗДОРОВЬЕ (Santé) ===== */
  {id:226,category:"sante",level:"A1",russian:"Мне плохо.",phonetic:"Mne plokho.",fr:"Je me sens mal.",en:"I feel unwell."},
  {id:227,category:"sante",level:"A1",russian:"Я заболел(а).",phonetic:"Ya zabolel(a).",fr:"Je suis malade.",en:"I am sick."},
  {id:228,category:"sante",level:"A1",russian:"У меня температура.",phonetic:"U menya temperatura.",fr:"J'ai de la fièvre.",en:"I have a fever."},
  {id:229,category:"sante",level:"A1",russian:"У меня болит голова.",phonetic:"U menya bolit golova.",fr:"J'ai mal à la tête.",en:"I have a headache."},
  {id:230,category:"sante",level:"A1",russian:"У меня болит живот.",phonetic:"U menya bolit zhivot.",fr:"J'ai mal au ventre.",en:"I have a stomach ache."},
  {id:231,category:"sante",level:"A1",russian:"У меня болит горло.",phonetic:"U menya bolit gorlo.",fr:"J'ai mal à la gorge.",en:"I have a sore throat."},
  {id:232,category:"sante",level:"A1",russian:"У меня кашель.",phonetic:"U menya kashel'.",fr:"J'ai une toux.",en:"I have a cough."},
  {id:233,category:"sante",level:"A1",russian:"У меня насморк.",phonetic:"U menya nasmork.",fr:"J'ai un rhume.",en:"I have a runny nose."},
  {id:234,category:"sante",level:"A1",russian:"У меня аллергия.",phonetic:"U menya allergiya.",fr:"J'ai une allergie.",en:"I have an allergy."},
  {id:235,category:"sante",level:"A1",russian:"Что со мной?",phonetic:"Chto so mnoy?",fr:"Qu'est-ce que j'ai ?",en:"What is wrong with me?"},
  {id:236,category:"sante",level:"A1",russian:"Что мне делать?",phonetic:"Chto mne delat'?",fr:"Que dois-je faire ?",en:"What should I do?"},
  {id:237,category:"sante",level:"A1",russian:"Мне нужно к врачу.",phonetic:"Mne nuzhno k vrachu.",fr:"J'ai besoin de voir un médecin.",en:"I need to see a doctor."},
  {id:238,category:"sante",level:"A1",russian:"Где ближайшая больница?",phonetic:"Gde blizhayshaya bol'nitsa?",fr:"Où est l'hôpital le plus proche ?",en:"Where is the nearest hospital?"},
  {id:239,category:"sante",level:"A1",russian:"Где поликлиника?",phonetic:"Gde poliklinika?",fr:"Où se trouve la clinique ?",en:"Where is the clinic?"},
  {id:240,category:"sante",level:"A1",russian:"Вызовите скорую помощь!",phonetic:"Vyzovite skoruyu pomoshch'!",fr:"Appelez les secours !",en:"Call an ambulance!"},
  {id:241,category:"sante",level:"A1",russian:"Мне срочно нужна помощь.",phonetic:"Mne srochno nuzhna pomoshch'.",fr:"J'ai urgemment besoin d'aide.",en:"I urgently need help."},
  {id:242,category:"sante",level:"A2",russian:"Когда приём у врача?",phonetic:"Kogda priyom u vracha?",fr:"Quand est le rendez-vous chez le médecin ?",en:"When is the doctor's appointment?"},
  {id:243,category:"sante",level:"A2",russian:"Мне нужен рецепт.",phonetic:"Mne nuzhen retsept.",fr:"J'ai besoin d'une ordonnance.",en:"I need a prescription."},
  {id:244,category:"sante",level:"A2",russian:"Какие лекарства мне принимать?",phonetic:"Kakiye lekarstva mne prinimat'?",fr:"Quels médicaments dois-je prendre ?",en:"What medicines should I take?"},
  {id:245,category:"sante",level:"B1",russian:"Есть ли побочные эффекты?",phonetic:"Est' li pobochnyye effekty?",fr:"Y a-t-il des effets secondaires ?",en:"Are there any side effects?"},
  {id:246,category:"sante",level:"A2",russian:"Как часто принимать лекарство?",phonetic:"Kak chasto prinimat' lekarstvo?",fr:"À quelle fréquence dois-je prendre le médicament ?",en:"How often should I take the medicine?"},
  {id:247,category:"sante",level:"A1",russian:"До еды или после?",phonetic:"Do yedy ili posle?",fr:"Avant ou après les repas ?",en:"Before or after meals?"},
  {id:248,category:"sante",level:"A2",russian:"Сколько дней принимать?",phonetic:"Skol'ko dney prinimat'?",fr:"Pendant combien de jours dois-je le prendre ?",en:"For how many days should I take it?"},
  {id:249,category:"sante",level:"A2",russian:"У вас есть обезболивающее?",phonetic:"U vas est' obezbolivayushcheye?",fr:"Avez-vous un analgésique ?",en:"Do you have a painkiller?"},
  {id:250,category:"sante",level:"A2",russian:"У вас есть жаропонижающее?",phonetic:"U vas est' zharoponizhaushcheye?",fr:"Avez-vous quelque chose contre la fièvre ?",en:"Do you have something for fever?"},
  {id:251,category:"sante",level:"A1",russian:"У вас есть пластырь?",phonetic:"U vas est' plastyr'?",fr:"Avez-vous du pansement ?",en:"Do you have a plaster?"},
  {id:252,category:"sante",level:"A1",russian:"У вас есть бинт?",phonetic:"U vas est' bint?",fr:"Avez-vous un bandage ?",en:"Do you have a bandage?"},
  {id:253,category:"sante",level:"A1",russian:"У вас есть градусник?",phonetic:"U vas est' gradusnik?",fr:"Avez-vous un thermomètre ?",en:"Do you have a thermometer?"},
  {id:254,category:"sante",level:"A1",russian:"У вас есть витамины?",phonetic:"U vas est' vitaminy?",fr:"Avez-vous des vitamines ?",en:"Do you have vitamins?"},
  {id:255,category:"sante",level:"B1",russian:"Работает ли аптека круглосуточно?",phonetic:"Rabotayet li apteka kruglosutochno?",fr:"Est-ce que la pharmacie est ouverte 24h/24 ?",en:"Is the pharmacy open 24 hours?"},
  {id:256,category:"sante",level:"A2",russian:"У меня головокружение.",phonetic:"U menya golovokruzheniye.",fr:"J'ai des vertiges.",en:"I feel dizzy."},
  {id:257,category:"sante",level:"A2",russian:"У меня слабость.",phonetic:"U menya slabost'.",fr:"Je me sens faible.",en:"I feel weak."},
  {id:258,category:"sante",level:"A2",russian:"У меня тошнота.",phonetic:"U menya toshnota.",fr:"J'ai des nausées.",en:"I feel nauseous."},
  {id:259,category:"sante",level:"B1",russian:"У меня сыпь.",phonetic:"U menya syp'.",fr:"J'ai une éruption cutanée.",en:"I have a rash."},
  {id:260,category:"sante",level:"B1",russian:"У меня зуд.",phonetic:"U menya zud.",fr:"J'ai des démangeaisons.",en:"I have itching."},
  {id:261,category:"sante",level:"B1",russian:"Мне трудно дышать.",phonetic:"Mne trudno dyshat'.",fr:"J'ai du mal à respirer.",en:"I have difficulty breathing."},
  {id:262,category:"sante",level:"B1",russian:"У меня высокое давление.",phonetic:"U menya vysokoye davleniye.",fr:"J'ai la tension élevée.",en:"I have high blood pressure."},
  {id:263,category:"sante",level:"B1",russian:"У меня низкое давление.",phonetic:"U menya nizkoye davleniye.",fr:"J'ai la tension basse.",en:"I have low blood pressure."},
  {id:264,category:"sante",level:"B1",russian:"Мне нужно сделать анализ крови.",phonetic:"Mne nuzhno sdelat' analiz krovi.",fr:"J'ai besoin d'une analyse de sang.",en:"I need a blood test."},
  {id:265,category:"sante",level:"B1",russian:"Мне нужно сделать рентген.",phonetic:"Mne nuzhno sdelat' rentgen.",fr:"J'ai besoin d'une radio.",en:"I need an X-ray."},
  {id:266,category:"sante",level:"B2",russian:"Мне нужна консультация специалиста.",phonetic:"Mne nuzhna konsul'tatsiya spetsialista.",fr:"J'ai besoin d'un avis spécialisé.",en:"I need a specialist's opinion."},
  {id:267,category:"sante",level:"B1",russian:"Когда я поправлюсь?",phonetic:"Kogda ya popravlyus'?",fr:"Quand vais-je aller mieux ?",en:"When will I get better?"},
  {id:268,category:"sante",level:"A2",russian:"Это серьёзно?",phonetic:"Eto ser'yozno?",fr:"Est-ce grave ?",en:"Is it serious?"},
  {id:269,category:"sante",level:"B1",russian:"Нужно ли ложиться в больницу?",phonetic:"Nuzhno li lozhit'sya v bol'nitsu?",fr:"Faut-il que j'aille à l'hôpital ?",en:"Do I need to be hospitalised?"},
  {id:270,category:"sante",level:"B2",russian:"Можно ли обойтись без операции?",phonetic:"Mozhno li oboytis' bez operatsii?",fr:"Peut-on éviter l'opération ?",en:"Can we avoid surgery?"},
  {id:271,category:"sante",level:"B2",russian:"Сколько времени займёт восстановление?",phonetic:"Skol'ko vremeni zaymyot vosstanovleniye?",fr:"Combien de temps prendra la récupération ?",en:"How long will recovery take?"},
  {id:272,category:"sante",level:"B1",russian:"Нужно ли соблюдать диету?",phonetic:"Nuzhno li soblyudat' diyetu?",fr:"Faut-il suivre un régime ?",en:"Do I need to follow a diet?"},
  {id:273,category:"sante",level:"B1",russian:"Какие продукты мне можно есть?",phonetic:"Kakiye produkty mne mozhno yest'?",fr:"Quels aliments puis-je manger ?",en:"What foods can I eat?"},
  {id:274,category:"sante",level:"A1",russian:"Мне стало лучше.",phonetic:"Mne stalo luchshe.",fr:"Je me sens mieux.",en:"I feel better."},

  /* ===== ЖИЛЬЁ (Logement) ===== */
  {id:275,category:"logement",level:"A1",russian:"Где находится прачечная?",phonetic:"Gde nakhoditsya prachechnaya?",fr:"Où se trouve la laverie ?",en:"Where is the laundry room?"},
  {id:276,category:"logement",level:"A1",russian:"У вас есть стиральная машина?",phonetic:"U vas est' stiralnaya mashina?",fr:"Avez-vous une machine à laver ?",en:"Do you have a washing machine?"},
  {id:277,category:"logement",level:"A1",russian:"Где можно постирать одежду?",phonetic:"Gde mozhno postrat' odezhdu?",fr:"Où puis-je laver mes vêtements ?",en:"Where can I wash my clothes?"},
  {id:278,category:"logement",level:"A1",russian:"У меня нет горячей воды.",phonetic:"U menya net goryachey vody.",fr:"Je n'ai pas d'eau chaude.",en:"I have no hot water."},
  {id:279,category:"logement",level:"A2",russian:"У меня проблемы с электричеством.",phonetic:"U menya problemy s elektrichestvom.",fr:"J'ai un problème d'électricité.",en:"I have an electricity problem."},
  {id:280,category:"logement",level:"A1",russian:"Свет не работает.",phonetic:"Svet ne rabotayet.",fr:"La lumière ne fonctionne pas.",en:"The light doesn't work."},
  {id:281,category:"logement",level:"A2",russian:"У меня течёт кран.",phonetic:"U menya techyot kran.",fr:"Mon robinet fuit.",en:"My tap is leaking."},
  {id:282,category:"logement",level:"A2",russian:"Нужно вызвать сантехника.",phonetic:"Nuzhno vyzzvat' santekhneka.",fr:"Il faut appeler un plombier.",en:"We need to call a plumber."},
  {id:283,category:"logement",level:"A1",russian:"Где находится мусорный бак?",phonetic:"Gde nakhoditsya musornyy bak?",fr:"Où se trouve la poubelle ?",en:"Where is the bin?"},
  {id:284,category:"logement",level:"A2",russian:"Когда вывозят мусор?",phonetic:"Kogda vyvozat musor?",fr:"Quand est-ce qu'on enlève les ordures ?",en:"When is the bin collected?"},
  {id:285,category:"logement",level:"A1",russian:"У вас есть пылесос?",phonetic:"U vas est' pylesos?",fr:"Avez-vous un aspirateur ?",en:"Do you have a vacuum cleaner?"},
  {id:286,category:"logement",level:"A2",russian:"Как включить отопление?",phonetic:"Kak vklyuchit' otopleniye?",fr:"Comment allumer le chauffage ?",en:"How do I turn on the heating?"},
  {id:287,category:"logement",level:"A1",russian:"В комнате слишком холодно.",phonetic:"V komnate slishkom kholodno.",fr:"Il fait trop froid dans la chambre.",en:"It is too cold in the room."},
  {id:288,category:"logement",level:"A1",russian:"В комнате слишком жарко.",phonetic:"V komnate slishkom zharko.",fr:"Il fait trop chaud dans la chambre.",en:"It is too hot in the room."},
  {id:289,category:"logement",level:"A1",russian:"Окно не закрывается.",phonetic:"Okno ne zakryvaetsya.",fr:"La fenêtre ne se ferme pas.",en:"The window won't close."},
  {id:290,category:"logement",level:"A1",russian:"Дверь не открывается.",phonetic:"Dver' ne otkryvaetsya.",fr:"La porte ne s'ouvre pas.",en:"The door won't open."},
  {id:291,category:"logement",level:"A1",russian:"Мне нужен ключ.",phonetic:"Mne nuzhen klyuch.",fr:"J'ai besoin d'une clé.",en:"I need a key."},
  {id:292,category:"logement",level:"A1",russian:"Где находится консьерж?",phonetic:"Gde nakhoditsya kon'serzh?",fr:"Où se trouve le concierge ?",en:"Where is the concierge?"},
  {id:293,category:"logement",level:"A2",russian:"Можно ли получить запасной ключ?",phonetic:"Mozhno li poluchit' zapasoy klyuch?",fr:"Puis-je obtenir une clé de rechange ?",en:"Can I get a spare key?"},
  {id:294,category:"logement",level:"A1",russian:"У вас есть Wi-Fi?",phonetic:"U vas est' Wi-Fi?",fr:"Avez-vous du Wi-Fi ?",en:"Do you have Wi-Fi?"},
  {id:295,category:"logement",level:"A1",russian:"Какой пароль от Wi-Fi?",phonetic:"Kakoy parol' ot Wi-Fi?",fr:"Quel est le mot de passe pour le Wi-Fi ?",en:"What is the Wi-Fi password?"},
  {id:296,category:"logement",level:"A1",russian:"Интернет не работает.",phonetic:"Internet ne rabotayet.",fr:"L'internet ne fonctionne pas.",en:"The internet is not working."},
  {id:297,category:"logement",level:"A1",russian:"Телефон не работает.",phonetic:"Telefon ne rabotayet.",fr:"Le téléphone ne fonctionne pas.",en:"The phone is not working."},
  {id:298,category:"logement",level:"A1",russian:"Мне нужно зарядить телефон.",phonetic:"Mne nuzhno zaryadit' telefon.",fr:"J'ai besoin de charger mon téléphone.",en:"I need to charge my phone."},
  {id:299,category:"logement",level:"A1",russian:"Где розетка?",phonetic:"Gde rozetka?",fr:"Où est la prise électrique ?",en:"Where is the power outlet?"},
  {id:300,category:"logement",level:"A1",russian:"У вас есть удлинитель?",phonetic:"U vas est' udlinitel'?",fr:"Avez-vous une multiprise ?",en:"Do you have an extension cord?"},
  {id:301,category:"logement",level:"A1",russian:"У вас есть лампочка?",phonetic:"U vas est' lampochka?",fr:"Avez-vous une ampoule ?",en:"Do you have a light bulb?"},
  {id:302,category:"logement",level:"A1",russian:"У вас есть инструменты?",phonetic:"U vas est' instrumenty?",fr:"Avez-vous des outils ?",en:"Do you have tools?"},
  {id:303,category:"logement",level:"A1",russian:"Это не моё.",phonetic:"Eto ne moyo.",fr:"Ce n'est pas à moi.",en:"This is not mine."},
  {id:304,category:"logement",level:"A1",russian:"Это ваше?",phonetic:"Eto vashe?",fr:"Est-ce à vous ?",en:"Is this yours?"},
  {id:305,category:"logement",level:"A1",russian:"Я забыл(а) свои вещи.",phonetic:"Ya zabyl(a) svoi veshchi.",fr:"J'ai oublié mes affaires.",en:"I forgot my belongings."},
  {id:306,category:"logement",level:"A1",russian:"Я потерял(а) ключи.",phonetic:"Ya poteryal(a) klyuchi.",fr:"J'ai perdu mes clés.",en:"I lost my keys."},
  {id:307,category:"logement",level:"A1",russian:"Будьте потише, пожалуйста.",phonetic:"Bud'te potishe, pozhaluysta.",fr:"Soyez plus silencieux, s'il vous plaît.",en:"Please be quieter."},
  {id:308,category:"logement",level:"A1",russian:"У вас шумно.",phonetic:"U vas shumno.",fr:"Vous faites trop de bruit.",en:"You are making too much noise."},
  {id:309,category:"logement",level:"A2",russian:"Когда заканчивается ремонт?",phonetic:"Kogda zakanchivaetsya remont?",fr:"Quand les travaux vont-ils se terminer ?",en:"When will the renovations end?"},
  {id:310,category:"logement",level:"A1",russian:"У вас есть гладильная доска?",phonetic:"U vas est' gladil'naya doska?",fr:"Avez-vous une planche à repasser ?",en:"Do you have an ironing board?"},
  {id:311,category:"logement",level:"A1",russian:"У вас есть утюг?",phonetic:"U vas est' utyug?",fr:"Avez-vous un fer à repasser ?",en:"Do you have an iron?"},
  {id:312,category:"logement",level:"A2",russian:"Как пользоваться этой техникой?",phonetic:"Kak pol'zovat'sya etoy tekhnikoy?",fr:"Comment utiliser cet appareil ?",en:"How do I use this appliance?"},
  {id:313,category:"logement",level:"A2",russian:"Можете показать, как это работает?",phonetic:"Mozhete pokazat', kak eto rabotayet?",fr:"Pouvez-vous me montrer comment ça fonctionne ?",en:"Can you show me how this works?"},
  {id:314,category:"logement",level:"A1",russian:"Всё понятно, спасибо!",phonetic:"Vsyo ponyatno, spasibo!",fr:"C'est clair, merci !",en:"All clear, thank you!"}
];
