/* EXTRA PHRASES — Part 4: Aéroport + Hôtel */
const PHRASES_EXTRA4 = [

  /* ===== АЭРОПОРТ (Aéroport) ===== */
  {id:315,category:"aeroport",level:"A1",russian:"Где находится регистрация на рейс?",phonetic:"Gde nakhoditsya registratsiya na reys?",fr:"Où se trouve le comptoir d'enregistrement ?",en:"Where is the check-in counter?"},
  {id:316,category:"aeroport",level:"A2",russian:"На какой стойке регистрироваться на рейс до Парижа?",phonetic:"Na kakoy stoyke registrirovat'sya na reys do Parizha?",fr:"À quel comptoir enregistrer pour le vol à destination de Paris ?",en:"At which counter do I check in for the flight to Paris?"},
  {id:317,category:"aeroport",level:"A1",russian:"Мой рейс задерживается?",phonetic:"Moy reys zaderzivayetsya?",fr:"Mon vol est-il retardé ?",en:"Is my flight delayed?"},
  {id:318,category:"aeroport",level:"A1",russian:"Мой рейс отменён.",phonetic:"Moy reys otmenyon.",fr:"Mon vol a été annulé.",en:"My flight has been cancelled."},
  {id:319,category:"aeroport",level:"A1",russian:"Где выход на посадку?",phonetic:"Gde vykhod na posadku?",fr:"Où est la porte d'embarquement ?",en:"Where is the boarding gate?"},
  {id:320,category:"aeroport",level:"A1",russian:"Во сколько начинается посадка?",phonetic:"Vo skol'ko nachinaletsya posadka?",fr:"À quelle heure commence l'embarquement ?",en:"What time does boarding start?"},
  {id:321,category:"aeroport",level:"A1",russian:"Где зона выдачи багажа?",phonetic:"Gde zona vydachi bagazha?",fr:"Où se trouve la zone de retrait des bagages ?",en:"Where is the baggage claim area?"},
  {id:322,category:"aeroport",level:"A1",russian:"Я потерял(а) свой багаж.",phonetic:"Ya poteryal(a) svoy bagazh.",fr:"J'ai perdu mes bagages.",en:"I lost my luggage."},
  {id:323,category:"aeroport",level:"A2",russian:"У меня один чемодан и ручная кладь.",phonetic:"U menya odin chemodan i ruchnaya klad'.",fr:"J'ai une valise et un bagage à main.",en:"I have one suitcase and hand luggage."},
  {id:324,category:"aeroport",level:"A2",russian:"Каков лимит веса багажа?",phonetic:"Kakov limit vesa bagazha?",fr:"Quelle est la limite de poids pour les bagages ?",en:"What is the luggage weight limit?"},
  {id:325,category:"aeroport",level:"A2",russian:"Мне нужен билет в один конец.",phonetic:"Mne nuzhen bilet v odin konets.",fr:"Je voudrais un billet aller simple.",en:"I need a one-way ticket."},
  {id:326,category:"aeroport",level:"A2",russian:"Мне нужен билет туда-обратно.",phonetic:"Mne nuzhen bilet tuda-obratno.",fr:"Je voudrais un billet aller-retour.",en:"I need a return ticket."},
  {id:327,category:"aeroport",level:"A1",russian:"Есть ли прямой рейс?",phonetic:"Est' li pryamoy reys?",fr:"Y a-t-il un vol direct ?",en:"Is there a direct flight?"},
  {id:328,category:"aeroport",level:"A1",russian:"Сколько времени длится перелёт?",phonetic:"Skol'ko vremeni dlitsya perelet?",fr:"Combien de temps dure le vol ?",en:"How long is the flight?"},
  {id:329,category:"aeroport",level:"A1",russian:"Где можно обменять деньги?",phonetic:"Gde mozhno obmenyat' den'gi?",fr:"Où puis-je échanger de l'argent ?",en:"Where can I exchange money?"},
  {id:330,category:"aeroport",level:"B1",russian:"Какой курс обмена?",phonetic:"Kakoy kurs obmena?",fr:"Quel est le taux d'échange ?",en:"What is the exchange rate?"},
  {id:331,category:"aeroport",level:"A1",russian:"Мне нужно такси до отеля.",phonetic:"Mne nuzhno taksi do otelya.",fr:"J'ai besoin d'un taxi pour aller à l'hôtel.",en:"I need a taxi to the hotel."},
  {id:332,category:"aeroport",level:"A1",russian:"У вас есть брошюры о городе?",phonetic:"U vas est' broshyury o gorode?",fr:"Avez-vous des brochures sur la ville ?",en:"Do you have brochures about the city?"},

  /* ===== ОТЕЛЬ (Hôtel) ===== */
  {id:333,category:"hotel",level:"A1",russian:"У вас есть Wi-Fi в отеле?",phonetic:"U vas est' Wi-Fi v otele?",fr:"Avez-vous du Wi-Fi dans l'hôtel ?",en:"Do you have Wi-Fi in the hotel?"},
  {id:334,category:"hotel",level:"A1",russian:"Во сколько заезд?",phonetic:"Vo skol'ko zayezd?",fr:"À quelle heure est l'enregistrement (check-in) ?",en:"What time is check-in?"},
  {id:335,category:"hotel",level:"A1",russian:"Во сколько выезд?",phonetic:"Vo skol'ko vyezd?",fr:"À quelle heure est le départ (check-out) ?",en:"What time is check-out?"},
  {id:336,category:"hotel",level:"A1",russian:"У меня забронирован номер.",phonetic:"U menya zabronirovan nomer.",fr:"J'ai une chambre réservée.",en:"I have a room reservation."},
  {id:337,category:"hotel",level:"A1",russian:"Моя фамилия…",phonetic:"Moya familiya…",fr:"Mon nom de famille est…",en:"My last name is…"},
  {id:338,category:"hotel",level:"A2",russian:"Можно посмотреть номер перед оплатой?",phonetic:"Mozhno posmotret' nomer pered oplatoy?",fr:"Puis-je voir la chambre avant de payer ?",en:"Can I see the room before paying?"},
  {id:339,category:"hotel",level:"A1",russian:"В номере есть кондиционер?",phonetic:"V nomere est' konditsioner?",fr:"La chambre a-t-elle la climatisation ?",en:"Does the room have air conditioning?"},
  {id:340,category:"hotel",level:"A1",russian:"В номере есть телевизор?",phonetic:"V nomere est' televizor?",fr:"La chambre a-t-elle une télévision ?",en:"Does the room have a TV?"},
  {id:341,category:"hotel",level:"A1",russian:"В номере есть ванная комната?",phonetic:"V nomere est' vannaya komnata?",fr:"La chambre a-t-elle une salle de bains ?",en:"Does the room have a bathroom?"},
  {id:342,category:"hotel",level:"A1",russian:"Сколько стоит номер за ночь?",phonetic:"Skol'ko stoit nomer za noch'?",fr:"Combien coûte la chambre par nuit ?",en:"How much does the room cost per night?"},
  {id:343,category:"hotel",level:"B1",russian:"Можно продлить проживание?",phonetic:"Mozhno prodlit' prozhivaniye?",fr:"Puis-je prolonger mon séjour ?",en:"Can I extend my stay?"},
  {id:344,category:"hotel",level:"A1",russian:"У вас есть свободные номера?",phonetic:"U vas est' svobodnye nomera?",fr:"Avez-vous des chambres disponibles ?",en:"Do you have any available rooms?"},
  {id:345,category:"hotel",level:"A1",russian:"Я хочу забронировать номер.",phonetic:"Ya khochu zabronirovat' nomer.",fr:"Je voudrais réserver une chambre.",en:"I would like to book a room."},
  {id:346,category:"hotel",level:"A1",russian:"На сколько дней?",phonetic:"Na skol'ko dney?",fr:"Pour combien de jours ?",en:"For how many days?"},
  {id:347,category:"hotel",level:"A1",russian:"На три дня.",phonetic:"Na tri dnya.",fr:"Pour trois jours.",en:"For three days."},
  {id:348,category:"hotel",level:"A1",russian:"С завтраком или без?",phonetic:"S zavtrakom ili bez?",fr:"Avec petit déjeuner ou sans ?",en:"With or without breakfast?"},
  {id:349,category:"hotel",level:"A1",russian:"Включён ли завтрак?",phonetic:"Vklyuchyon li zavtrak?",fr:"Le petit déjeuner est-il inclus ?",en:"Is breakfast included?"},
  {id:350,category:"hotel",level:"A1",russian:"Где находится ресторан отеля?",phonetic:"Gde nakhoditsya restoran otelya?",fr:"Où se trouve le restaurant de l'hôtel ?",en:"Where is the hotel restaurant?"},
  {id:351,category:"hotel",level:"A1",russian:"Во сколько завтрак?",phonetic:"Vo skol'ko zavtrak?",fr:"À quelle heure est le petit déjeuner ?",en:"What time is breakfast?"},
  {id:352,category:"hotel",level:"A2",russian:"Можно заказать еду в номер?",phonetic:"Mozhno zakazat' yedu v nomer?",fr:"Puis-je commander de la nourriture dans ma chambre ?",en:"Can I order food to my room?"},
  {id:353,category:"hotel",level:"A1",russian:"Где лифт?",phonetic:"Gde lift?",fr:"Où se trouve l'ascenseur ?",en:"Where is the lift?"},
  {id:354,category:"hotel",level:"A1",russian:"Мой ключ не работает.",phonetic:"Moy klyuch ne rabotayet.",fr:"Ma clé ne fonctionne pas.",en:"My key doesn't work."},
  {id:355,category:"hotel",level:"A2",russian:"Можно поменять номер?",phonetic:"Mozhno pomenyat' nomer?",fr:"Puis-je changer de chambre ?",en:"Can I change my room?"},
  {id:356,category:"hotel",level:"A1",russian:"В номере слишком шумно.",phonetic:"V nomere slishkom shumno.",fr:"Il fait trop de bruit dans la chambre.",en:"The room is too noisy."},
  {id:357,category:"hotel",level:"A2",russian:"Мне нужны дополнительные полотенца.",phonetic:"Mne nuzhny dopolnitel'nyye polotentsa.",fr:"J'ai besoin de serviettes supplémentaires.",en:"I need extra towels."},
  {id:358,category:"hotel",level:"A2",russian:"Мне нужно постельное бельё.",phonetic:"Mne nuzhno postel'noye bel'yo.",fr:"J'ai besoin de draps.",en:"I need bed linen."},
  {id:359,category:"hotel",level:"A1",russian:"У вас есть сейф?",phonetic:"U vas est' seyf?",fr:"Avez-vous un coffre-fort ?",en:"Do you have a safe?"},
  {id:360,category:"hotel",level:"A1",russian:"Как им пользоваться?",phonetic:"Kak im pol'zovat'sya?",fr:"Comment l'utiliser ?",en:"How do I use it?"},
  {id:361,category:"hotel",level:"A1",russian:"Где находится парковка?",phonetic:"Gde nakhoditsya parkovka?",fr:"Où se trouve le parking ?",en:"Where is the car park?"},
  {id:362,category:"hotel",level:"A1",russian:"Парковка платная?",phonetic:"Parkovka platnaya?",fr:"Le parking est-il payant ?",en:"Is the car park paid?"},
  {id:363,category:"hotel",level:"A1",russian:"Вы можете вызвать такси?",phonetic:"Vy mozhete vyzyvat' taksi?",fr:"Pouvez-vous appeler un taxi ?",en:"Can you call a taxi?"}
];
