/* EXTRA PHRASES — Part 7: Education, Conversation avancée, Travail professionnel */
const PHRASES_EXTRA7 = [

  /* ===== ОБРАЗОВАНИЕ (Education) - Nouvelles phrases ===== */
  {id:448,category:"education",level:"A2",russian:"Когда нужно сдать домашнее задание?",phonetic:"Kogda nuzhno sdat' domashneye zadaniye?",fr:"Quand faut-il rendre le devoir ?",en:"When do we need to submit the homework?"},
  {id:449,category:"education",level:"A2",russian:"Можно сдать позже?",phonetic:"Mozhno sdat' pozzhe?",fr:"Est-il possible de le rendre plus tard ?",en:"Is it possible to submit it later?"},
  {id:450,category:"education",level:"A2",russian:"Я забыл(а) сдать задание.",phonetic:"Ya zabyl(a) sdat' zadaniye.",fr:"J'ai oublié de rendre le devoir.",en:"I forgot to submit the assignment."},
  {id:451,category:"education",level:"A2",russian:"Мы будем писать тест на следующем занятии?",phonetic:"My budem pisat' test na sleduyushchem zanyatii?",fr:"Allons-nous passer un test au prochain cours ?",en:"Will we have a test in the next class?"},
  {id:452,category:"education",level:"A2",russian:"Сколько вопросов будет в тесте?",phonetic:"Skol'ko voprosov budet v teste?",fr:"Combien de questions y aura-t-il dans le test ?",en:"How many questions will be in the test?"},
  {id:453,category:"education",level:"A2",russian:"Можно работать в группе?",phonetic:"Mozhno rabotat' v gruppe?",fr:"Est-il permis de travailler en groupe ?",en:"Is it allowed to work in a group?"},
  {id:454,category:"education",level:"A1",russian:"Кто в моей группе?",phonetic:"Kto v moyey gruppe?",fr:"Qui est dans mon groupe ?",en:"Who is in my group?"},
  {id:455,category:"education",level:"A2",russian:"Давайте обсудим задание вместе.",phonetic:"Davayte obsudim zadaniye vmeste.",fr:"Discutons du devoir ensemble.",en:"Let's discuss the assignment together."},
  {id:456,category:"education",level:"A1",russian:"Поможешь мне с упражнением?",phonetic:"Pomozhesh' mne s uprazhneniyem?",fr:"Peux-tu m'aider avec l'exercice ?",en:"Can you help me with the exercise?"},
  {id:457,category:"education",level:"A1",russian:"Я закончил(а) упражнение.",phonetic:"Ya zakonchil(a) uprazhneniye.",fr:"J'ai terminé l'exercice.",en:"I finished the exercise."},
  {id:458,category:"education",level:"A2",russian:"У меня есть идея по проекту.",phonetic:"U menya yest' ideya po proyektu.",fr:"J'ai une idée pour le projet.",en:"I have an idea for the project."},
  {id:459,category:"education",level:"A2",russian:"Когда нужно представить проект?",phonetic:"Kogda nuzhno predstavit' proyekt?",fr:"Quand faut-il présenter le projet ?",en:"When do we need to present the project?"},

  /* ===== РАЗГОВОР (Conversation) - Niveau avancé ===== */
  {id:460,category:"conversation",level:"B2",russian:"На самом деле, я не совсем согласен(сна).",phonetic:"Na samom dele, ya ne sovsem soglasen(sna).",fr:"En fait, je ne suis pas tout à fait d'accord.",en:"Actually, I don't quite agree."},
  {id:461,category:"conversation",level:"B2",russian:"Если честно, мне это кажется немного странным.",phonetic:"Yesli chestno, mne eto kazhetsya nemnogo strannym.",fr:"Pour être honnête, je trouve ça un peu étrange.",en:"To be honest, I find this a bit strange."},
  {id:462,category:"conversation",level:"B1",russian:"Это кажется мне логичным.",phonetic:"Eto kazhetsya mne logichnym.",fr:"Cela me paraît logique.",en:"This seems logical to me."},
  {id:463,category:"conversation",level:"B2",russian:"Я понимаю вашу точку зрения, но…",phonetic:"Ya ponimayu vashu tochku zreniya, no…",fr:"Je comprends votre point de vue, mais…",en:"I understand your point of view, but…"},
  {id:464,category:"conversation",level:"B2",russian:"Позвольте мне переформулировать это.",phonetic:"Pozvol'te mne pereformulirovat' eto.",fr:"Permettez-moi de reformuler ça.",en:"Allow me to rephrase this."},
  {id:465,category:"conversation",level:"B2",russian:"Подводя итог, вы говорите, что…",phonetic:"Podvodya itog, vy govorite, chto…",fr:"Pour résumer, vous dites que…",en:"To summarize, you're saying that…"},
  {id:466,category:"conversation",level:"B2",russian:"Если я правильно понимаю, вы хотите сказать, что…",phonetic:"Yesli ya pravil'no ponimayu, vy khotite skazat', chto…",fr:"Si je comprends bien, vous voulez dire que…",en:"If I understand correctly, you mean that…"},
  {id:467,category:"conversation",level:"B2",russian:"Это именно то, что я собирался(ась) предложить.",phonetic:"Eto imenno to, chto ya sobiralsya(as') predlozhit'.",fr:"C'est exactement ce que j'allais proposer.",en:"That's exactly what I was going to suggest."},
  {id:468,category:"conversation",level:"B1",russian:"Я хотел(а) бы узнать об этом побольше.",phonetic:"Ya khotel(a) by uznat' ob etom pobol'she.",fr:"J'aimerais en savoir plus à ce sujet.",en:"I would like to know more about this."},
  {id:469,category:"conversation",level:"B2",russian:"Не могли бы вы уточнить свою мысль?",phonetic:"Ne mogli by vy utochnit' svoyu mysl'?",fr:"Pourriez-vous préciser votre idée ?",en:"Could you clarify your thought?"},
  {id:470,category:"conversation",level:"B1",russian:"Это зависит от нескольких факторов.",phonetic:"Eto zavisit ot neskol'kikh faktorov.",fr:"Cela dépend de plusieurs facteurs.",en:"It depends on several factors."},
  {id:471,category:"conversation",level:"B1",russian:"В большинстве случаев — да.",phonetic:"V bol'shinstve sluchayev — da.",fr:"Dans la plupart des cas, oui.",en:"In most cases, yes."},
  {id:472,category:"conversation",level:"B2",russian:"Есть исключения из этого правила.",phonetic:"Yest' isklyucheniya iz etogo pravila.",fr:"Il y a des exceptions à cette règle.",en:"There are exceptions to this rule."},
  {id:473,category:"conversation",level:"B2",russian:"Это не так просто, как кажется.",phonetic:"Eto ne tak prosto, kak kazhetsya.",fr:"Ce n'est pas aussi simple que ça en a l'air.",en:"It's not as simple as it seems."},
  {id:474,category:"conversation",level:"B2",russian:"Я разрываюсь между двумя вариантами.",phonetic:"Ya razryvayus' mezhdu dvumya variantami.",fr:"Je suis partagé(e) entre deux options.",en:"I'm torn between two options."},
  {id:475,category:"conversation",level:"B1",russian:"Я колеблюсь между… и…",phonetic:"Ya koleblyus' mezhdu… i…",fr:"J'hésite entre… et…",en:"I hesitate between… and…"},
  {id:476,category:"conversation",level:"B1",russian:"Стоит попробовать.",phonetic:"Stoit poprobovat'.",fr:"Ça vaut la peine d'essayer.",en:"It's worth trying."},
  {id:477,category:"conversation",level:"B1",russian:"Нет смысла волноваться сейчас.",phonetic:"Net smysla volnovat'sya seychas.",fr:"Ça ne sert à rien de s'inquiéter maintenant.",en:"There's no point worrying now."},
  {id:478,category:"conversation",level:"B1",russian:"Лучше подождать немного.",phonetic:"Luchshe podozhdat' nemnogo.",fr:"Il vaut mieux attendre un peu.",en:"It's better to wait a bit."},
  {id:479,category:"conversation",level:"B2",russian:"Боюсь, это невозможно.",phonetic:"Boyus', eto nevozmozhno.",fr:"Je crains que ce ne soit pas possible.",en:"I'm afraid that's not possible."},
  {id:480,category:"conversation",level:"B2",russian:"Мне жаль, но я не могу это принять.",phonetic:"Mne zhal', no ya ne mogu eto prinyat'.",fr:"Je suis désolé(e), mais je ne peux pas accepter ça.",en:"I'm sorry, but I can't accept that."},

  /* ===== Gratitude et excuses avancées ===== */
  {id:481,category:"conversation",level:"B2",russian:"Я вам очень благодарен(а) за помощь.",phonetic:"Ya vam ochen' blagodaren(a) za pomoshch'.",fr:"Je vous suis très reconnaissant(e) pour votre aide.",en:"I'm very grateful to you for your help."},
  {id:482,category:"conversation",level:"B2",russian:"Это было очень любезно с вашей стороны.",phonetic:"Eto bylo ochen' lyubezno s vashey storony.",fr:"C'était très aimable de votre part.",en:"That was very kind of you."},
  {id:483,category:"conversation",level:"B2",russian:"Я вам очень признателен(а).",phonetic:"Ya vam ochen' priznatel'en(a).",fr:"Je vous en suis très reconnaissant(e).",en:"I'm very grateful to you."},
  {id:484,category:"conversation",level:"B1",russian:"Прошу прощения за опоздание.",phonetic:"Proshu proshcheniya za opozdaniye.",fr:"Veuillez m'excuser pour le retard.",en:"Please excuse me for being late."},
  {id:485,category:"conversation",level:"B1",russian:"Прошу прощения за невежливость.",phonetic:"Proshu proshcheniya za nevezhlivost'.",fr:"Je m'excuse d'avoir été impoli(e).",en:"I apologize for being rude."},
  {id:486,category:"conversation",level:"B1",russian:"Жаль, что я это сказал(а).",phonetic:"Zhal', chto ya eto skazal(a).",fr:"Je regrette d'avoir dit ça.",en:"I regret saying that."},
  {id:487,category:"conversation",level:"B2",russian:"Это не входило в мои намерения.",phonetic:"Eto ne vkhodilo v moi namereniya.",fr:"Ce n'était pas mon intention.",en:"That wasn't my intention."},

  /* ===== Expressions de surprise et d'opinion ===== */
  {id:488,category:"conversation",level:"B1",russian:"Это меня действительно удивляет!",phonetic:"Eto menya deystvitel'no udivlyayet!",fr:"Ça m'étonne vraiment !",en:"That really surprises me!"},
  {id:489,category:"conversation",level:"B2",russian:"Я бы никогда этого не предположил(а).",phonetic:"Ya by nikogda etogo ne predpolozhil(a).",fr:"Je n'aurais jamais imaginé ça.",en:"I would never have imagined that."},
  {id:490,category:"conversation",level:"B1",russian:"Неожиданно, но интересно.",phonetic:"Neozhidanno, no interesno.",fr:"C'est inattendu, mais intéressant.",en:"It's unexpected, but interesting."},
  {id:491,category:"conversation",level:"B1",russian:"Мне трудно в это поверить.",phonetic:"Mne trudno v eto poverit'.",fr:"J'ai du mal à y croire.",en:"I find it hard to believe."},
  {id:492,category:"conversation",level:"B2",russian:"В это едва можно поверить!",phonetic:"V eto yedva mozhno poverit'!",fr:"C'est à peine croyable !",en:"It's barely believable!"},
  {id:493,category:"conversation",level:"B2",russian:"Мне это кажется немного чрезмерным.",phonetic:"Mne eto kazhetsya nemnogo chrezmernym.",fr:"Ça me paraît un peu excessif.",en:"That seems a bit excessive to me."},
  {id:494,category:"conversation",level:"B1",russian:"Я считаю это разумным.",phonetic:"Ya schitayu eto razumnym.",fr:"Je trouve ça raisonnable.",en:"I think that's reasonable."},
  {id:495,category:"conversation",level:"B2",russian:"Это отличная инициатива.",phonetic:"Eto otlichnaya initsiativa.",fr:"C'est une excellente initiative.",en:"That's an excellent initiative."},
  {id:496,category:"conversation",level:"B2",russian:"Это заслуживает более детального рассмотрения.",phonetic:"Eto zasluzhivayet boleye detal'nogo rassmotreniya.",fr:"Cela mérite d'être examiné plus en détail.",en:"This deserves more detailed consideration."},
  {id:497,category:"conversation",level:"B2",russian:"Я ценю вашу откровенность.",phonetic:"Ya tsenyu vashu otkrovennost'.",fr:"J'apprécie votre franchise.",en:"I appreciate your frankness."},
  {id:498,category:"conversation",level:"B2",russian:"Это весомый аргумент.",phonetic:"Eto vesomyy argument.",fr:"C'est un argument valable.",en:"That's a valid argument."},
  {id:499,category:"conversation",level:"B2",russian:"Ваше предложение очень уместное.",phonetic:"Vashe predlozheniye ochen' umestnoye.",fr:"Votre suggestion est très pertinente.",en:"Your suggestion is very relevant."},

  /* ===== РАБОТА (Travail) - Réunions et management ===== */
  {id:500,category:"travail",level:"B1",russian:"Добрый день, давайте начнём встречу.",phonetic:"Dobryy den', davayte nachnёm vstrechu.",fr:"Bonjour, commençons la réunion.",en:"Good day, let's start the meeting."},
  {id:501,category:"travail",level:"B1",russian:"Какова повестка дня?",phonetic:"Kakova povestka dnya?",fr:"Quel est l'ordre du jour ?",en:"What is the agenda?"},
  {id:502,category:"travail",level:"B1",russian:"Сначала обсудим первый пункт.",phonetic:"Snachala obsudim pervyy punkt.",fr:"Commençons par discuter du premier point.",en:"Let's first discuss the first point."},
  {id:503,category:"travail",level:"B2",russian:"У кого-нибудь есть дополнительные вопросы по этому пункту?",phonetic:"U kogo-nibud' yest' dopolnitel'nyye voprosy po etomu punktu?",fr:"Est-ce que quelqu'un a des questions supplémentaires sur ce point ?",en:"Does anyone have additional questions on this point?"},
  {id:504,category:"travail",level:"B1",russian:"Позвольте мне уточнить.",phonetic:"Pozvol'te mne utochnit'.",fr:"Permettez-moi de clarifier.",en:"Allow me to clarify."},
  {id:505,category:"travail",level:"B2",russian:"Я хотел(а) бы вернуться к предыдущему вопросу.",phonetic:"Ya khotel(a) by vernut'sya k predydushchemu voprosu.",fr:"Je voudrais revenir à la question précédente.",en:"I would like to return to the previous question."},
  {id:506,category:"travail",level:"B1",russian:"Давайте подведём итоги.",phonetic:"Davayte podvedёm itogi.",fr:"Faisons le bilan.",en:"Let's summarize."},
  {id:507,category:"travail",level:"B1",russian:"Каковы наши следующие шаги?",phonetic:"Kakovy nashi sleduyushchiye shagi?",fr:"Quels sont nos prochains pas ?",en:"What are our next steps?"},
  {id:508,category:"travail",level:"B1",russian:"Кто будет отвечать за этот проект?",phonetic:"Kto budet otvechat' za etot proyekt?",fr:"Qui sera responsable de ce projet ?",en:"Who will be responsible for this project?"},
  {id:509,category:"travail",level:"B2",russian:"Мне нужно больше времени для анализа.",phonetic:"Mne nuzhno bol'she vremeni dlya analiza.",fr:"J'ai besoin de plus de temps pour l'analyse.",en:"I need more time for analysis."},
  {id:510,category:"travail",level:"B2",russian:"Сроки сжатые, но выполнимые.",phonetic:"Sroki szhatyye, no vypolnimyye.",fr:"Les délais sont serrés, mais réalisables.",en:"The deadlines are tight, but achievable."},
  {id:511,category:"travail",level:"B1",russian:"Мы укладываемся в график.",phonetic:"My ukladyvayemsya v grafik.",fr:"Nous respectons le calendrier.",en:"We're keeping to the schedule."},
  {id:512,category:"travail",level:"B1",russian:"Мы отстаём от графика.",phonetic:"My otstayom ot grafika.",fr:"Nous sommes en retard par rapport au calendrier.",en:"We're behind schedule."},
  {id:513,category:"travail",level:"B2",russian:"Нужно скорректировать план.",phonetic:"Nuzhno skorrektirovat' plan.",fr:"Il faut ajuster le plan.",en:"We need to adjust the plan."},
  {id:514,category:"travail",level:"B2",russian:"Какие ресурсы нам понадобятся?",phonetic:"Kakiye resursy nam ponadobyatsya?",fr:"Quelles ressources nous faudra-t-il ?",en:"What resources will we need?"},
  {id:515,category:"travail",level:"B1",russian:"Бюджет утверждён.",phonetic:"Byudzhet utverzhdon.",fr:"Le budget est approuvé.",en:"The budget is approved."},
  {id:516,category:"travail",level:"B2",russian:"Нам нужно дополнительное финансирование.",phonetic:"Nam nuzhno dopolnitel'noye finansirovaniye.",fr:"Nous avons besoin d'un financement supplémentaire.",en:"We need additional funding."},
  {id:517,category:"travail",level:"B2",russian:"Каковы ключевые показатели эффективности?",phonetic:"Kakovy klyuchevyye pokazateli effektivnosti?",fr:"Quels sont les indicateurs clés de performance ?",en:"What are the key performance indicators?"},
  {id:518,category:"travail",level:"B1",russian:"Отчёт готов, я пришлю его по электронной почте.",phonetic:"Otchёt gotov, ya prishlu yego po elektronnoy pochte.",fr:"Le rapport est prêt, je l'enverrai par courriel.",en:"The report is ready, I'll send it by email."},
  {id:519,category:"travail",level:"B1",russian:"Пришлите мне детали в письме.",phonetic:"Prishite mne detali v pis'me.",fr:"Envoyez-moi les détails par courriel.",en:"Send me the details by email."},
  {id:520,category:"travail",level:"B1",russian:"Давайте запланируем следующую встречу.",phonetic:"Davayte zaplaniruyem sleduyushchuyu vstrechu.",fr:"Planifions la prochaine réunion.",en:"Let's plan the next meeting."},
  {id:521,category:"travail",level:"A2",russian:"На какой день вам удобно?",phonetic:"Na kakoy den' vam udobno?",fr:"Quel jour vous convient ?",en:"What day is convenient for you?"},
  {id:522,category:"travail",level:"A2",russian:"В четверг в 14:00 подойдёт?",phonetic:"V chetverg v 14:00 podoydёt?",fr:"Jeudi à 14 h 00 vous convient-il ?",en:"Would Thursday at 2:00 PM work?"},
  {id:523,category:"travail",level:"B1",russian:"К сожалению, в это время я занят(а).",phonetic:"K sozhaleniyu, v eto vremya ya zanyat(a).",fr:"Malheureusement, je suis occupé(e) à ce moment-là.",en:"Unfortunately, I'm busy at that time."},
  {id:524,category:"travail",level:"A2",russian:"Давайте перенесём на пятницу.",phonetic:"Davayte perenesёm na pyatnitsu.",fr:"Déplaçons à vendredi.",en:"Let's move it to Friday."},
  {id:525,category:"travail",level:"B1",russian:"Я пришлю приглашение в календарь.",phonetic:"Ya prishlu priglasheniye v kalendar'.",fr:"J'enverrai une invitation dans le calendrier.",en:"I'll send a calendar invitation."},
  {id:526,category:"travail",level:"B1",russian:"Прошу подтвердить ваше участие.",phonetic:"Proshu podtverdit' vashe uchastiye.",fr:"Veuillez confirmer votre participation.",en:"Please confirm your participation."},
  {id:527,category:"travail",level:"B2",russian:"Коллеги, прошу вас высказаться.",phonetic:"kollegi, proshu vas vyskazat'sya.",fr:"Collègues, je vous invite à exprimer votre avis.",en:"Colleagues, I invite you to express your opinion."},
  {id:528,category:"travail",level:"B1",russian:"Я согласен(сна) с вашим предложением.",phonetic:"Ya soglasen(sna) s vashim predlozheniyem.",fr:"Je suis d'accord avec votre proposition.",en:"I agree with your proposal."},
  {id:529,category:"travail",level:"B1",russian:"У меня есть некоторые сомнения.",phonetic:"U menya yest' nekotoryye somneniya.",fr:"J'ai quelques doutes.",en:"I have some doubts."},
  {id:530,category:"travail",level:"B2",russian:"Это перспективная идея, но требует доработки.",phonetic:"Eto perspektivnaya ideya, no trebuyет dorabotki.",fr:"C'est une idée prometteuse, mais elle nécessite des améliorations.",en:"It's a promising idea, but it needs refinement."},
  {id:531,category:"travail",level:"B2",russian:"Давайте рассмотрим альтернативные варианты.",phonetic:"Davayte rassmotrim al'ternativnyye varianty.",fr:"Examinons des options alternatives.",en:"Let's consider alternative options."},
  {id:532,category:"travail",level:"B2",russian:"Каковы риски этого решения?",phonetic:"Kakovy riski etogo resheniya?",fr:"Quels sont les risques de cette décision ?",en:"What are the risks of this decision?"},
  {id:533,category:"travail",level:"B2",russian:"Мы минимизировали возможные риски.",phonetic:"My minimizirovali vozmozhnyye riski.",fr:"Nous avons minimisé les risques possibles.",en:"We have minimized possible risks."},
  {id:534,category:"travail",level:"B2",russian:"Нужно учесть все факторы.",phonetic:"Nuzhno uchest' vse faktory.",fr:"Il faut prendre en compte tous les facteurs.",en:"We need to consider all factors."},
  {id:535,category:"travail",level:"B2",russian:"Каковы долгосрочные перспективы?",phonetic:"Kakovy dolgosrochnyye perspektivy?",fr:"Quelles sont les perspectives à long terme ?",en:"What are the long-term prospects?"},
  {id:536,category:"travail",level:"B2",russian:"Это стратегически важное решение.",phonetic:"Eto strategicheski vazhnoye resheniye.",fr:"C'est une décision stratégique.",en:"This is a strategic decision."},
  {id:537,category:"travail",level:"B2",russian:"Нам нужно согласовать это с руководством.",phonetic:"Nam nuzhno soglasovat' eto s rukovodstvom.",fr:"Nous devons soumettre cela à la direction.",en:"We need to coordinate this with management."},
  {id:538,category:"travail",level:"B1",russian:"Руководство одобрило план.",phonetic:"Rukovodstvo odobrilo plan.",fr:"La direction a approuvé le plan.",en:"Management approved the plan."},
  {id:539,category:"travail",level:"B2",russian:"Нужно получить одобрение от юридического отдела.",phonetic:"Nuzhno poluchit' odobreniye ot yuridicheskogo otdela.",fr:"Il faut obtenir l'approbation du service juridique.",en:"We need to get approval from the legal department."},
  {id:540,category:"travail",level:"B2",russian:"Отдел кадров предоставит данные.",phonetic:"Otdel kadrov predostavit dannye.",fr:"Le service des ressources humaines fournira les données.",en:"HR will provide the data."},
  {id:541,category:"travail",level:"B2",russian:"Технический отдел решит эту проблему.",phonetic:"Tekhnicheskiy otdel reshit etu problemu.",fr:"Le service technique résoudra ce problème.",en:"The technical department will solve this problem."},
  {id:542,category:"travail",level:"B2",russian:"Маркетинговая кампания стартует в следующем месяце.",phonetic:"Marketingovaya kampaniya startuyет v sleduyushchem mesyatse.",fr:"La campagne marketing démarrera le mois prochain.",en:"The marketing campaign will start next month."},
  {id:543,category:"travail",level:"B1",russian:"Продажи выросли на 15%.",phonetic:"Prodazhi vyrosli na 15%.",fr:"Les ventes ont augmenté de 15%.",en:"Sales increased by 15%."},
  {id:544,category:"travail",level:"B1",russian:"Мы достигли целевых показателей.",phonetic:"My dostigli tselevykh pokazateley.",fr:"Nous avons atteint les objectifs.",en:"We reached the target indicators."},
  {id:545,category:"travail",level:"B2",russian:"Нам нужно повысить эффективность.",phonetic:"Nam nuzhno povysit' effektivnost'.",fr:"Nous devons améliorer l'efficacité.",en:"We need to improve efficiency."}
];