/* EXTRA PHRASES — Part 2: Nourriture (new) + Shopping */
const PHRASES_EXTRA2 = [

  /* ===== ЕДА — nouvelles phrases au restaurant ===== */
  {id:139,category:"nourriture",level:"A1",russian:"Можно меню, пожалуйста?",phonetic:"Mozhno menyu, pozhaluysta?",fr:"La carte, s'il vous plaît ?",en:"Can I have the menu, please?"},
  {id:140,category:"nourriture",level:"A1",russian:"Я готов(а) сделать заказ.",phonetic:"Ya gotov(a) sdelat' zakaz.",fr:"Je suis prêt(e) à commander.",en:"I am ready to order."},
  {id:141,category:"nourriture",level:"A1",russian:"Что вы порекомендуете?",phonetic:"Chto vy porekomenduyete?",fr:"Que recommandez-vous ?",en:"What do you recommend?"},
  {id:142,category:"nourriture",level:"A1",russian:"Я бы хотел(а)…",phonetic:"Ya by khotel(a)…",fr:"Je voudrais…",en:"I would like…"},
  {id:143,category:"nourriture",level:"A1",russian:"Принесите, пожалуйста, воду.",phonetic:"Prinesite, pozhaluysta, vodu.",fr:"Apportez de l'eau, s'il vous plaît.",en:"Please bring some water."},
  {id:144,category:"nourriture",level:"A1",russian:"Без льда, пожалуйста.",phonetic:"Bez l'da, pozhaluysta.",fr:"Sans glace, s'il vous plaît.",en:"Without ice, please."},
  {id:145,category:"nourriture",level:"A1",russian:"Со льдом, пожалуйста.",phonetic:"So l'dom, pozhaluysta.",fr:"Avec glace, s'il vous plaît.",en:"With ice, please."},
  {id:146,category:"nourriture",level:"A1",russian:"Ещё кофе, пожалуйста.",phonetic:"Yeshchyo kofe, pozhaluysta.",fr:"Encore du café, s'il vous plaît.",en:"More coffee, please."},
  {id:147,category:"nourriture",level:"A1",russian:"Можно оплатить картой?",phonetic:"Mozhno oplatit' kartoy?",fr:"Puis-je payer par carte ?",en:"Can I pay by card?"},
  {id:148,category:"nourriture",level:"A1",russian:"Можно оплатить наличными?",phonetic:"Mozhno oplatit' nalichnymi?",fr:"Puis-je payer en espèces ?",en:"Can I pay in cash?"},
  {id:149,category:"nourriture",level:"A1",russian:"Это очень вкусно!",phonetic:"Eto ochen' vkusno!",fr:"C'est très délicieux !",en:"This is very delicious!"},
  {id:150,category:"nourriture",level:"A1",russian:"Мне не нравится.",phonetic:"Mne ne nravitsya.",fr:"Je n'aime pas ça.",en:"I don't like this."},
  {id:151,category:"nourriture",level:"A1",russian:"Слишком солёно.",phonetic:"Slishkom solyono.",fr:"Trop salé.",en:"Too salty."},
  {id:152,category:"nourriture",level:"A1",russian:"Слишком остро.",phonetic:"Slishkom ostro.",fr:"Trop épicé.",en:"Too spicy."},
  {id:153,category:"nourriture",level:"A1",russian:"Слишком сладко.",phonetic:"Slishkom sladko.",fr:"Trop sucré.",en:"Too sweet."},
  {id:154,category:"nourriture",level:"A2",russian:"Можно заменить гарнир?",phonetic:"Mozhno zamenit' garnir?",fr:"Puis-je remplacer le légume ?",en:"Can I change the side dish?"},
  {id:155,category:"nourriture",level:"A1",russian:"У вас есть вегетарианские блюда?",phonetic:"U vas est' vegetarianskiye blyuda?",fr:"Avez-vous des plats végétariens ?",en:"Do you have vegetarian dishes?"},
  {id:156,category:"nourriture",level:"A2",russian:"У вас есть безглютеновые блюда?",phonetic:"U vas est' bezglyutenovyye blyuda?",fr:"Avez-vous des plats sans gluten ?",en:"Do you have gluten-free dishes?"},
  {id:157,category:"nourriture",level:"A1",russian:"Я аллергик.",phonetic:"Ya allergeek.",fr:"Je suis allergique.",en:"I am allergic."},
  {id:158,category:"nourriture",level:"A1",russian:"На что у вас аллергия?",phonetic:"Na chto u vas allergiya?",fr:"À quoi êtes-vous allergique ?",en:"What are you allergic to?"},
  {id:159,category:"nourriture",level:"A1",russian:"У меня аллергия на орехи.",phonetic:"U menya allergiya na orekhi.",fr:"Je suis allergique aux noix.",en:"I am allergic to nuts."},
  {id:160,category:"nourriture",level:"A1",russian:"Завтрак.",phonetic:"Zavtrak.",fr:"Le petit déjeuner.",en:"Breakfast."},
  {id:161,category:"nourriture",level:"A1",russian:"Обед.",phonetic:"Obed.",fr:"Le déjeuner.",en:"Lunch."},
  {id:162,category:"nourriture",level:"A1",russian:"Ужин.",phonetic:"Uzhin.",fr:"Le dîner.",en:"Dinner."},
  {id:163,category:"nourriture",level:"A1",russian:"Закуска.",phonetic:"Zakuska.",fr:"Une entrée.",en:"A starter."},
  {id:164,category:"nourriture",level:"A1",russian:"Основное блюдо.",phonetic:"Osnovnoye blyudo.",fr:"Un plat principal.",en:"A main course."},
  {id:165,category:"nourriture",level:"A1",russian:"Десерт.",phonetic:"Desert.",fr:"Un dessert.",en:"A dessert."},
  {id:166,category:"nourriture",level:"A1",russian:"Напиток.",phonetic:"Napitok.",fr:"Une boisson.",en:"A drink."},
  {id:167,category:"nourriture",level:"A1",russian:"Минеральная вода.",phonetic:"Mineral'naya voda.",fr:"De l'eau minérale.",en:"Mineral water."},
  {id:168,category:"nourriture",level:"A1",russian:"Газированная вода.",phonetic:"Gazirovannaya voda.",fr:"De l'eau gazeuse.",en:"Sparkling water."},
  {id:169,category:"nourriture",level:"A1",russian:"Негазированная вода.",phonetic:"Negazirovannaya voda.",fr:"De l'eau non gazeuse.",en:"Still water."},
  {id:170,category:"nourriture",level:"A1",russian:"Сок.",phonetic:"Sok.",fr:"Un jus.",en:"A juice."},
  {id:171,category:"nourriture",level:"A1",russian:"Чай.",phonetic:"Chay.",fr:"Du thé.",en:"Tea."},
  {id:172,category:"nourriture",level:"A1",russian:"Чёрный чай.",phonetic:"Chyornyy chay.",fr:"Du thé noir.",en:"Black tea."},
  {id:173,category:"nourriture",level:"A1",russian:"Зелёный чай.",phonetic:"Zelonyy chay.",fr:"Du thé vert.",en:"Green tea."},
  {id:174,category:"nourriture",level:"A1",russian:"Кофе.",phonetic:"Kofe.",fr:"Du café.",en:"Coffee."},
  {id:175,category:"nourriture",level:"A1",russian:"Эспрессо.",phonetic:"Espresso.",fr:"Un espresso.",en:"An espresso."},
  {id:176,category:"nourriture",level:"A1",russian:"Американо.",phonetic:"Amerikano.",fr:"Un café américain.",en:"An Americano."},
  {id:177,category:"nourriture",level:"A1",russian:"Капучино.",phonetic:"Kapuchino.",fr:"Un cappuccino.",en:"A cappuccino."},
  {id:178,category:"nourriture",level:"A1",russian:"Латте.",phonetic:"Latte.",fr:"Un latte.",en:"A latte."},
  {id:179,category:"nourriture",level:"A1",russian:"Хлеб.",phonetic:"Khleb.",fr:"Du pain.",en:"Bread."},
  {id:180,category:"nourriture",level:"A1",russian:"Салат.",phonetic:"Salat.",fr:"Une salade.",en:"A salad."},
  {id:181,category:"nourriture",level:"A1",russian:"Суп.",phonetic:"Sup.",fr:"Une soupe.",en:"Soup."},
  {id:182,category:"nourriture",level:"A1",russian:"Мясо.",phonetic:"Myaso.",fr:"De la viande.",en:"Meat."},
  {id:183,category:"nourriture",level:"A1",russian:"Рыба.",phonetic:"Ryba.",fr:"Du poisson.",en:"Fish."},
  {id:184,category:"nourriture",level:"A1",russian:"Овощи.",phonetic:"Ovoshchi.",fr:"Des légumes.",en:"Vegetables."},
  {id:185,category:"nourriture",level:"A1",russian:"Фрукты.",phonetic:"Frukty.",fr:"Des fruits.",en:"Fruits."},
  {id:186,category:"nourriture",level:"A1",russian:"Мороженое.",phonetic:"Morozhenoye.",fr:"De la glace.",en:"Ice cream."},
  {id:187,category:"nourriture",level:"A1",russian:"Торт.",phonetic:"Tort.",fr:"Un gâteau.",en:"A cake."},

  /* ===== ПОКУПКИ (Shopping) ===== */
  {id:188,category:"shopping",level:"A1",russian:"У вас есть…?",phonetic:"U vas est'…?",fr:"Avez-vous… ?",en:"Do you have…?"},
  {id:189,category:"shopping",level:"A1",russian:"Где я могу найти…?",phonetic:"Gde ya mogu nayti…?",fr:"Où puis-je trouver… ?",en:"Where can I find…?"},
  {id:190,category:"shopping",level:"A2",russian:"У вас есть это в другом размере?",phonetic:"U vas est' eto v drugom razmere?",fr:"Avez-vous ceci dans une autre taille ?",en:"Do you have this in another size?"},
  {id:191,category:"shopping",level:"A2",russian:"У вас есть это в другом цвете?",phonetic:"U vas est' eto v drugom tsvete?",fr:"Avez-vous ceci dans une autre couleur ?",en:"Do you have this in another colour?"},
  {id:192,category:"shopping",level:"A1",russian:"Это на распродаже?",phonetic:"Eto na rasprodazhe?",fr:"Est-ce en solde ?",en:"Is this on sale?"},
  {id:193,category:"shopping",level:"A1",russian:"Есть ли скидка?",phonetic:"Est' li skidka?",fr:"Y a-t-il une réduction ?",en:"Is there a discount?"},
  {id:194,category:"shopping",level:"A1",russian:"Это слишком дорого.",phonetic:"Eto slishkom dorogo.",fr:"C'est trop cher.",en:"This is too expensive."},
  {id:195,category:"shopping",level:"A2",russian:"Можете сделать скидку?",phonetic:"Mozhete sdelat' skidku?",fr:"Pouvez-vous faire une réduction ?",en:"Can you give me a discount?"},
  {id:196,category:"shopping",level:"A1",russian:"Я просто смотрю.",phonetic:"Ya prosto smotryu.",fr:"Je regarde juste.",en:"I am just looking."},
  {id:197,category:"shopping",level:"A1",russian:"Мне нужно подумать.",phonetic:"Mne nuzhno podumat'.",fr:"J'ai besoin de réfléchir.",en:"I need to think about it."},
  {id:198,category:"shopping",level:"A1",russian:"Я возьму это.",phonetic:"Ya voz'mu eto.",fr:"Je vais prendre ceci.",en:"I will take this."},
  {id:199,category:"shopping",level:"A1",russian:"Я не буду это покупать.",phonetic:"Ya ne budu eto pokupat'.",fr:"Je ne vais pas acheter ceci.",en:"I am not going to buy this."},
  {id:200,category:"shopping",level:"A1",russian:"Где примерочная?",phonetic:"Gde primerochnaya?",fr:"Où est la cabine d'essayage ?",en:"Where is the fitting room?"},
  {id:201,category:"shopping",level:"A1",russian:"Можно примерить?",phonetic:"Mozhno primerit'?",fr:"Puis-je essayer ?",en:"Can I try this on?"},
  {id:202,category:"shopping",level:"A1",russian:"Где кассы?",phonetic:"Gde kassy?",fr:"Où sont les caisses ?",en:"Where are the checkouts?"},
  {id:203,category:"shopping",level:"A1",russian:"Дайте, пожалуйста, чек.",phonetic:"Dayte, pozhaluysta, chek.",fr:"Donnez-moi le reçu, s'il vous plaît.",en:"Please give me the receipt."},
  {id:204,category:"shopping",level:"A2",russian:"У вас есть гарантия?",phonetic:"U vas est' garantiya?",fr:"Avez-vous une garantie ?",en:"Do you have a warranty?"},
  {id:205,category:"shopping",level:"B1",russian:"Как долго действует гарантия?",phonetic:"Kak dolgo deystvuyet garantiya?",fr:"Combien de temps dure la garantie ?",en:"How long is the warranty valid?"},
  {id:206,category:"shopping",level:"A2",russian:"Можно обменять товар?",phonetic:"Mozhno obmenyat' tovar?",fr:"Puis-je échanger cet article ?",en:"Can I exchange this item?"},
  {id:207,category:"shopping",level:"A2",russian:"Можно вернуть товар?",phonetic:"Mozhno vernut' tovar?",fr:"Puis-je rendre cet article ?",en:"Can I return this item?"},
  {id:208,category:"shopping",level:"A2",russian:"У вас есть упаковка в подарок?",phonetic:"U vas est' upakovka v podarok?",fr:"Avez-vous un emballage cadeau ?",en:"Do you have gift wrapping?"},
  {id:209,category:"shopping",level:"A1",russian:"Это в наличии?",phonetic:"Eto v nalichii?",fr:"Est-ce disponible ?",en:"Is this in stock?"},
  {id:210,category:"shopping",level:"B1",russian:"Когда будет в наличии?",phonetic:"Kogda budet v nalichii?",fr:"Quand sera-t-il disponible ?",en:"When will it be in stock?"},
  {id:211,category:"shopping",level:"A2",russian:"У вас есть доставка?",phonetic:"U vas est' dostavka?",fr:"Offrez-vous la livraison ?",en:"Do you offer delivery?"},
  {id:212,category:"shopping",level:"A2",russian:"Сколько стоит доставка?",phonetic:"Skol'ko stoit dostavka?",fr:"Combien coûte la livraison ?",en:"How much does delivery cost?"},
  {id:213,category:"shopping",level:"A2",russian:"Когда будет доставка?",phonetic:"Kogda budet dostavka?",fr:"Quand aura lieu la livraison ?",en:"When will the delivery arrive?"},
  {id:214,category:"shopping",level:"A1",russian:"У вас есть каталог?",phonetic:"U vas est' katalog?",fr:"Avez-vous un catalogue ?",en:"Do you have a catalogue?"},
  {id:215,category:"shopping",level:"A1",russian:"Молоко.",phonetic:"Moloko.",fr:"Du lait.",en:"Milk."},
  {id:216,category:"shopping",level:"A1",russian:"Яйца.",phonetic:"Yaytsa.",fr:"Des œufs.",en:"Eggs."},
  {id:217,category:"shopping",level:"A1",russian:"Сыр.",phonetic:"Syr.",fr:"Du fromage.",en:"Cheese."},
  {id:218,category:"shopping",level:"A1",russian:"Колбаса.",phonetic:"Kolbasa.",fr:"Du saucisson.",en:"Sausage."},
  {id:219,category:"shopping",level:"A1",russian:"Вода.",phonetic:"Voda.",fr:"De l'eau.",en:"Water."},
  {id:220,category:"shopping",level:"A1",russian:"Сахар.",phonetic:"Sakhar.",fr:"Du sucre.",en:"Sugar."},
  {id:221,category:"shopping",level:"A1",russian:"Соль.",phonetic:"Sol'.",fr:"Du sel.",en:"Salt."},
  {id:222,category:"shopping",level:"A1",russian:"Перец.",phonetic:"Perets.",fr:"Du poivre.",en:"Pepper."},
  {id:223,category:"shopping",level:"A1",russian:"Рис.",phonetic:"Ris.",fr:"Du riz.",en:"Rice."},
  {id:224,category:"shopping",level:"A1",russian:"Макароны.",phonetic:"Makarony.",fr:"Des pâtes.",en:"Pasta."},
  {id:225,category:"shopping",level:"A1",russian:"Конфета.",phonetic:"Konfeta.",fr:"Un bonbon.",en:"A sweet."}
];
